version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-test-server
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro